resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: Autopickup
  type: git
  source:
    branch: master
    uri: https://ThePhilderbeast@bitbucket.org/ThePhilderbeast/autopickup.git

- name: github
  type: git
  source:
    branch: master
    uri: git@github.com:ThePhilderbeast/AutoPickup.git
    private_key: ((private_repo_key))

- name: discord-notification
  type: slack-notification
  source:
    url: https://discordapp.com/api/webhooks/356928845116604416/mCzSi2wOdGPIll51hv9ubRGeR3z9LWxTQar2Ow-ZgeMFm5T0QAKVVdZPRgak3K7r2GnF/slack

jobs:
- name: build
  plan:
  - get: Autopickup
    trigger: true
  - task: build
    file: Autopickup/ci/concourse.yml
  - put: github
    params: {repository: Autopickup }
  - put: discord-notification
    params:
      text: |
        Master built successfully https://concourse.philderbeast.com/builds/$BUILD_ID